apiVersion: v1
kind: LimitRange
metadata:
  name: lr-defaults
  namespace: demo-namespace
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      maxLimitRequestRatio:
        cpu: "2"
        memory: "2"
