apiVersion: v1
kind: Pod
metadata:
  name: stress-1
  namespace: demo-namespace
spec:
  containers:
  - name: app
    image: ghcr.io/seoyhaein/stress_app:v1
    args: ["--mem", "200", "--cpu", "1"]  # 200Mi 메모리, 1 goroutine
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 400m
        memory: 300Mi
