apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /mnt/kind-demo # 호스트 디렉터리
        containerPath: /mnt/kind-demo # 노드 컨테이너 안 경로
  - role: worker
    extraMounts:
      - hostPath: /mnt/kind-demo
        containerPath: /mnt/kind-demo
